#pragma once

#include <windows.h>
#include <PowrProf.h>
#include <iostream>
#include <TlHelp32.h>
#include <fstream>
#include <filesystem>
#include <string>
#include <sstream>
#include <vector>
#include <algorithm>
#include <iterator>
#include <thread>
#include <chrono>
#include <wininet.h>
#include <ctime>
#include <iomanip>
#include <array>
#include <tchar.h>
#include <psapi.h>
#include <stdio.h>
#include <stdlib.h>
